### ISSUE TITLE
3.11 statistics are wrong

### ISSUE THREAD

**Issue by rffontenelle** [rffontenelle/docspush-transifex#17]
https://app.transifex.com/python-doc/communication/d:21c99e36-2d28-4aea-9788-78b5037319de/?q=project%3Apython-newest

**Comment by m-aciek** [comment]
In my opinion that's not only statistics. Please note for Brazilian Portugese also some translations are gone: https://app.transifex.com/python-doc/python-311/language/pt_BR/. It looks like "grouped translation memory" is a feature in Premium plan only, and probably we should make the translations propagation and push to Transifex manually for each language? I am temporarily disabling the pull from Transifex for 3.11 in Git Actions for Polish to keep the translations until we will be able to resolve it.

**Comment by rffontenelle** [comment]
Yeah, we I said statistics I meant strings that should show up as translated are not.

Theorically I simply pushed the translstion of resources from previous python-newest (prior 3.11) to the python-311 project.

As soon as I fix the \\N ilegal character issue, I'll work on that.

**Comment by m-aciek** [comment]
The statistics looks much better now, current value for 3.11 progress [is 6.63%](https://app.transifex.com/python-doc/python-311/dashboard/) 🎉 

The small caveat is that we lose metadata with translators. In https://github.com/python/python-docs-pl/commit/dca90b1c538c5ba5c391384d8e87dda6f998b652 the GH Actions fetched the data from 3.11 on Transifex. I'm not sure if it is even possible to fix it, I don't know the exact process, but if you see a simple fix for that, sharing that would be appreciated.

**Comment by rffontenelle** [comment]
@m-aciek To push your translations to Transifex, simply run `tx push -l pl -t`. Requirements are: having tx client installed, run it from the language team repository having an up-to-date .tx/config, a pot/ directory (see how this repo's workflow generate it) and the PO files.

To push a specific resource, append the \<project_slug>.\<resource_slug>. e.g. `tx push -l pl -t python-311.library--codecs python-311.library--re`

**Comment by rffontenelle** [comment]
Will close this then. If anything is missing, we reopen it. Thanks for bringing this up, @m-aciek
